- name: Setup Travel Router
  hosts: localhost
  connection: local
  become: yes

  # Default variables (in case script is run without them)
  vars:
    wifi_ssid: "TravelRouterDefault"
    wifi_password: "ChangeMe123!"
    wifi_channel: "36"
    country_code: "US"
    admin_password: "secret"
    # Detect config location (Bookworm vs Bullseye)
    config_file: "{{ '/boot/firmware/config.txt' if query('file', '/boot/firmware/config.txt') else '/boot/config.txt' }}"

  tasks:
    # --- STEP 1: SYSTEM PREP ---
    
    # Task A: Update the OS
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    # Task B: Install specific tools
    - name: Install required dependencies
      apt:
        pkg:
          - i2c-tools
          - util-linux
          - python3-pip
          - git
          - php-cli  # Added this so the password hash task works
        state: present

    # --- STEP 2: HARDWARE (I2C & RTC) ---
    - name: Enable I2C interface
      lineinfile:
        path: "{{ config_file }}"
        regexp: '^dtparam=i2c_arm='
        line: 'dtparam=i2c_arm=on'
        state: present

    - name: Add RTC Overlay
      lineinfile:
        path: "{{ config_file }}"
        line: 'dtoverlay=i2c-rtc,ds3231'
        state: present

    - name: Load i2c-dev module
      lineinfile:
        path: /etc/modules
        line: 'i2c-dev'
        state: present

    # --- STEP 3: INSTALL RASPAP ---
    - name: Install RaspAP (Non-interactive)
      shell: curl -sL https://install.raspap.com | bash -s -- -y
      args:
        creates: /var/www/html/index.php

    # --- STEP 4: CONFIGURATION ---
    
    # 1. Generate the Hash using PHP
    - name: Generate Admin Password Hash
      shell: php -r 'echo password_hash("{{ admin_password }}", PASSWORD_BCRYPT);'
      register: admin_pass_hash
      changed_when: false

    # 2. Write the Hashed Password (UNCOMMENTED & FIXED)
    - name: Update RaspAP Admin Password
      copy:
        dest: /etc/raspap/raspap.auth
        # Writes "admin:$2y$10$..." to the file
        content: "admin:{{ admin_pass_hash.stdout }}"
        owner: root
        group: www-data
        mode: '0640'

    # 3. Configure DNS (Cloudflare + Google)
    - name: Configure DHCP DNS Servers (1.1.1.1, 8.8.8.8)
      lineinfile:
        path: /etc/dnsmasq.d/090_raspap.conf
        regexp: '^dhcp-option=6'
        line: 'dhcp-option=6,1.1.1.1,8.8.8.8'
        state: present
      notify: Restart Dnsmasq
    
    # 4. Deploy WiFi Config
    - name: Deploy Custom Hostapd Config
      template:
        src: "{{ playbook_dir }}/files/hostapd.conf.j2"
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Hostapd

    # 5. Deploy LED Scripts
    - name: Deploy LED Status Script
      copy:
        src: "{{ playbook_dir }}/files/router_status.sh"
        dest: /usr/local/bin/router_status.sh
        mode: '0755'

    - name: Create LED Service
      copy:
        dest: /etc/systemd/system/router-led.service
        content: |
          [Unit]
          Description=Router Status LED indicator
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/router_status.sh
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
      notify: Reload Systemd

    - name: Enable LED Service
      systemd:
        name: router-led
        enabled: yes
        state: started

  # --- HANDLERS (Fixed missing entries) ---
  handlers:
    - name: Restart Hostapd
      systemd:
        name: hostapd
        state: restarted

    # This was missing and causing your error
    - name: Restart Dnsmasq
      systemd:
        name: dnsmasq
        state: restarted

    - name: Reload Systemd
      systemd:
        daemon_reload: yes